version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    volumes:
      - static:/code/docker_django/staticfiles
      - media:/code/docker_django/media
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/docker_django/staticfiles
      - media:/code/docker_django/media
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static:
  media:



